### ISSUE TITLE
Button on toolbar to make it easier to get to options?

### ISSUE THREAD

**Issue by Fogest** [hadalin/chrome-hidefedora#30]
Some users may not even know there is an options page, or may find it annoying to get to the options page. You have to go to the extensions page, find the extension, and then hit options. A button could be added to the toolbar that when click opens the options page. 

If someone doesn't like the button there it is very easy to just right click it and hide the button anyway, so it shouldn't annoy anyone.

**Comment by scottrobertson** [comment]
@hadalin i agree, adding a button for the sake of it is not a good option.
