### ISSUE TITLE
Make button more hidden or a confirmation?

### ISSUE THREAD

**Issue by Fogest** [hadalin/chrome-hidefedora#37]
Right now it is really easy for someone to go through and just hit the report button on everyone on a YouTube video. This makes it easy for the fedora users to quickly make a large amount of false reports. To discourage such a behaviour I such putting the button back in the drop down like it originally was, OR make a popup to confirm their intent. 

With almost 30 000 users on the Chrome extension alone it means there have been an increasing number of false reports as people just easily go through the comments reporting them all.

**Comment by hadalin** [comment]
Added a confirmation. Tried to add the button to the dropdown, but it's too much hassle. Changed button text though so it doesn't take so much space.
