### ISSUE TITLE
Banned words don't always work

### ISSUE THREAD

**Issue by random6969** [hadalin/chrome-hidefedora#42]
I've noticed that if a banned word, such as "r/",  is is present near the closing of a comment, which can only be revealed by clicking "show more", than the comment itself is not blocked. This is an issue, since many fedora wearers avoid using keywords such as "le Reddit" and moderator of "r/..." until the closing of their long-winded comment. This leads to some of their comments still being shown. 

It's also possible I am simply not using the banned words list correctly. I am assuming that if I add "r/" to the list, all comments including words such as "/r/feminism" or "/r/racism" or so on will be blocked since they include "r/" somewhere in the comment.

**Comment by hadalin** [comment]
I think the problem is with escaping html characters. Will take a look when I get home.

**Comment by hadalin** [comment]
This should work now.

**Comment by hadalin** [comment]
@random6969 I must warn you though that some sites like ```www.example.com/arrr/index.php``` will also get removed.
