### ISSUE TITLE
Option to disable global blacklist

### ISSUE THREAD

**Issue by Fogest** [hadalin/chrome-hidefedora#43]
The author the article on [ghacks](http://www.ghacks.net/2015/01/17/how-to-hide-annoying-comments-on-youtube-automatically/) suggested the following: 

>Hide Fedora works well both in Firefox and in Google Chrome. The one thing that I dislike is that you don't have control over the global blacklist. An option to decide whether you want to use it or not would certainly be appreciated by users of the add-on.

Think this is a good idea? Allow the user to have the option to only use the local list if they'd prefer?

**Comment by hadalin** [comment]
I'm not sure about this. The black list is the essence of the extension.

**Comment by Kektklik** [comment]
or at least give the user an option to have a whitelist, which will allow them to see certain users. No "button" functionality necessary.. just a text box in the settings area that will override the global blacklist settings.

Relevant issue: certain popular youtubers (over 100k subs) are blacklisted. Kshaway being one of them.

**Comment by Fogest** [comment]
@Kektklik The extension has not been updated in awhile so not sure if such a feature like this would be added. I have removed the ban on Kshaway as it looks like it was a mistake ban, however if you see other popular Youtubers blocked by it, or people you feel should not be blocked feel free to submit an appeal for their account: http://jhvisser.com/hidefedora/appeal
