### ISSUE TITLE
Minimize hit on host

### ISSUE THREAD

**Issue by Fogest** [hadalin/chrome-hidefedora#44]
Is it possible to add in some kind of time checking thing. As in check how old the cached copy of the json file is that is stored locally in Google chrome. So my idea here is the following:

When you grab a new json, locally save a time stamp of when you last grabbed the json file. Make it only grab a new one if the last one grabbed is more than say a 12 hours old, or a day old. 

I may be serving a cached file, which reduces the computation power the host requires, however dealing with that many requests itself is still a lot for my host to handle. This would also save the user some data and speed up load times as they don't need to grab new data every time. 

We are almost to 60 000 users on Chrome alone and as we grow there are just going to be more and more requests. It would be nice to reduce the amount of requests if possible.

**Comment by hadalin** [comment]
It could be done, but 12 hours seems quite a lot. We could start with one hour and then increase if it's necessary.

**Comment by Fogest** [comment]
I would say maybe 3 hours then. I am not sure if an hour is enough.

**Comment by hadalin** [comment]
Maybe even better than time check would be number of videos played.

**Comment by Fogest** [comment]
I was thinking about that originally, however what if someone doesn't watch a video for multiple days?

**Comment by hadalin** [comment]
Instant JSON grab could be a paid feature.

**Comment by Fogest** [comment]
That could work. Maybe it standardly updates everyday or every 12 hours but
if you pay it is instant.
