### ISSUE TITLE
Report and Ban button appears nowhere

### ISSUE THREAD

**Issue by kamehameshaw** [hadalin/chrome-hidefedora#49]
I've spent the better part of an hour working on getting this extension to work and every indication i see  is that it should be working but i keep seeing the atrocious youtube comments. Is this out of date? or do i need to change some chrome setting? 

Thanks

**Comment by Fogest** [comment]
Are you seeing this button on comments at all? 

![http://i.imgur.com/el9JWjw.png](http://i.imgur.com/el9JWjw.png)

**Comment by kamehameshaw** [comment]
Nope, i read that i hover over comments and it appears but i dont see it at all. I have disabled all extensions. Updated chrome, still no luck.

**Comment by Fogest** [comment]
Are you able to load the following URL fine: 

https://jhvisser.com/hidefedora/reports/profiles.json

If so, do you see a long list of mostly numbers?

**Comment by kamehameshaw** [comment]
It loaded a long list of numbers

**Comment by Fogest** [comment]
Can you give a link to the video you are trying it on that is not working?

**Comment by kamehameshaw** [comment]
https://www.youtube.com/watch?v=18kqcczy6MQ

https://www.youtube.com/watch?v=6-Wi_WMPZSA

https://www.youtube.com/watch?v=TnWOiTIqv6U

there is 3 of them i saw today.

**Comment by Fogest** [comment]
If you are feeling up to it, it would be great if you could try the following out. I have made sure everything regarding the website is working (I am the web developer, not the extension maker). The requests are being made successfully. So this is some kind of extension issue it looks like. 

The videos you linked are all having the offending comments blocked for me. 

Here is a set of steps that may help us debug your problem. 

Open up the Chrome Developer Panel (hit CTRL + SHIFT + I to open it).

Navigate to one of those URL's you provided. Scroll down and make sure the comments load up. 

Now click on the "Console" tab on the Chrome Developer panel:
![http://i.imgur.com/98vc6eq.png](http://i.imgur.com/98vc6eq.png)

Use the drop down in here and change the frame to "Hide Fedora" one:
![http://i.imgur.com/1jjmBZd.png](http://i.imgur.com/1jjmBZd.png)

Now  simply enter into the console:
```
chrome.storage.local.get(function(result){console.log(result)})
```

You should get an output that looks like this:
![http://i.imgur.com/rbVXsey.png](http://i.imgur.com/rbVXsey.png)

Expands the "Object" by using those little arrow symbols. You will now have something looking somewhat like this:
![http://i.imgur.com/5TIlzdg.png](http://i.imgur.com/5TIlzdg.png)

You don't need to expand them all, just do something like in the image. If possible take a screenshot of these results and post them on here. If the results look different than mine still post them as this may lead us to what the problem is. 

I know this is asking a lot, however it is difficult to determine the error as it is working for me.

**Comment by kamehameshaw** [comment]
I followed the instructions and got this result 

![hf](https://cloud.githubusercontent.com/assets/11358652/6539565/5fef5ef0-c434-11e4-9028-512e834bac20.PNG)

i am also seeing this error on youtube videos, not sure what is causing it
![hf2](https://cloud.githubusercontent.com/assets/11358652/6539572/7aa86458-c434-11e4-92eb-db96206ed095.PNG)

**Comment by Fogest** [comment]
You sure it isn't removing anything? Looks like it would be.

**Comment by kamehameshaw** [comment]
Failed to load resource: net::ERR_FAILED

I get this error constantly on youtube, even with all addons besides hide fedora.

Java is updated, chrome is updated. i'm at a loss.

**Comment by Fogest** [comment]
Try our add-on out on Firefox or Opera and see if it works there or not

**Comment by goct** [comment]
Same problem here. The Firefox version works for me.

**Comment by Fogest** [comment]
@hadalin will have to look into this more. The only change in the past month has been the URL's however I have confirmed these are working.

**Comment by hadalin** [comment]
What OS and Chrome version are you using?

**Comment by goct** [comment]
Windows 8.1
I was on Chrome Version 40.0.2214.115 m, and hit the update button when I checked the version, so now I'm on Version 41.0.2272.76 m. The issue still exists for me on this version.

**Comment by Fogest** [comment]
@goct the code between the Firefox version and Chrome version are almost identical. If it works on Firefox it should be working on Chrome.

**Comment by hadalin** [comment]
@Fogest Well not necessarily. The API is quite different.

 I'm using 41.0.2272.76 on OS X and it works fine.

**Comment by Fogest** [comment]
@hadalin that is true. I am using Version 41.0.2272.74 beta-m on Windows 8.1 without issues.

Maybe @goct should run the same thing I instructed the other user to run to ensure the storage is working correctly?

**Comment by goct** [comment]
I feel a little silly now. I just did the "Restore settings to their original defaults" option in Chrome and the extension looks to be working fine now.

**Comment by Fogest** [comment]
@goct seems weird that you'd need to do that to fix the extension. Something must be breaking somewhere. @hadalin would the URL change have caused issues? The new URL likely outputs the profile id's in a different order than the old URL was. I mean the JSON format is the same, just the ID's themselves may have been mix and matched. I am not sure if this messes with the way you are loading in profiles?

**Comment by hadalin** [comment]
@Fogest no, the order is not important. If there was no HF button, then the extension did not load properly IMO.

**Comment by kamehameshaw** [comment]
I was messing with chrome today and discovered something weird. When i am logged out of chrome, like when you do a full restore of settings the plugin works, after logging in the plugin stops.

**Comment by hadalin** [comment]
@kamehameshaw It's true. I'm finally able to reproduce this. Thanks.

**Comment by hadalin** [comment]
Ok, it stops working if you log out.

**Comment by hadalin** [comment]
@kamehameshaw @goct I think I found out what the problem is. If you log out of Chrome and open extensions settings page, you'll notice there is no Hide Fedora (and possibly any other extension besides Google ones) installed. You either need to install Hide Fedora when signed out or log back in and it should work again.

**Comment by paleguy** [comment]
I updated chrome, tried to reinstall the addon while logged out, while logged in, still nothing. In the extensions page it says "Active" but it just doesn't work. Actually it doesnt work on Firefox as well now that i checked, what am i possibly doing wrong? Until 1 week ago it was doing just fine

**Comment by trashcanman2000** [comment]
Same here. Tried above steps. Not showing button or hiding previous trolls from youtube. Showing as active in extensions

**Comment by hadalin** [comment]
@trashcanman2000 what OS, what Chrome version?

**Comment by trashcanman2000** [comment]
Windows 7, Ultimate Edition,  service pack 1, 64bit.
Chrome Version 40.0.2214.115 m

**Comment by hadalin** [comment]
@trashcanman2000 can you update to Chrome 41 and check again?

**Comment by trashcanman2000** [comment]
Just did. Still not working.

**Comment by hadalin** [comment]
@trashcanman2000 does it work if you're logged in or it doesn't work at all?

**Comment by trashcanman2000** [comment]
Doesn't work at all.

**Comment by hadalin** [comment]
@trashcanman2000 well if you by any chance figure it out, please do tell. Works for me.

**Comment by trashcanman2000** [comment]
Will do

**Comment by dotted** [comment]
Same issue for me, it doesn't even show up in the javascript console.

**Comment by Fogest** [comment]
@dotted [Try resetting your Google Chrome settings](http://www.howtogeek.com/171924/how-to-reset-your-web-browser-to-its-default-settings/)

**Comment by dotted** [comment]
Seems [HTTP Everywhere](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp) was the culprit

**Comment by Fogest** [comment]
@dotted good to know. That is odd that is caused issues because we are using an HTTPS connection to get the fedora data.

**Comment by dotted** [comment]
I decided to reenable HTTPS Everywhere, but Hide Fedora is still working after doing it - so I'm not sure any more. But given how error prone HTTPS Everywhere tends to be I wouldn't be surprised if it is due some really obscure conflict.

**Comment by Calmiche** [comment]
I've been fighting with this same problem for several months.  I finally went to "Settings > Disconnect your Google Account > " and selected the option to delete all passwords, extensions and history.  When I signed back into my Google account, HF worked fine.  (It also re-downloaded my shortcuts and remembered passwords and re-installed my extensions automatically.)

I've tried deactivating and reactivating Chrome before to fix this, but it did nothing.  As far as I can tell, you have to delete everything to get HF working again.

Strangely, it also installed a couple new extensions for Google Slides and Google Sheets that weren't there before.

Windows 8.1
64-bit
Chrome 41.0.2272.101 m

**Comment by Fogest** [comment]
@Calmiche glad you got it sorted out! Google Slides and Google Sheets are the Chrome default extensions I believe.

**Comment by revoltic** [comment]
is there anything we can do to block berta lovejoy or any fedorette trolls?

**Comment by SXRWahrheit** [comment]
I'm not seeing the option in the comments to hide specific users anymore, and vvvortic's comments are showing up again. I'd really like to not have to reset my browser.

![2016-03-20 13_24_22-developer tools - https___www youtube com_watch_v 8loaxtjf9f4](https://cloud.githubusercontent.com/assets/774463/13906215/1655e048-ee9f-11e5-8763-b0585dc94b43.png)

**Comment by Fogest** [comment]
@SXRWahrheit  you're right, I don't see it there anymore either. @hadalin do you want to take a look at this? YouTube may have changed their code a little?

**Comment by hadalin** [comment]
Hi. Little busy at the moment, but I'll try to find some time for this.

**Comment by Fogest** [comment]
I have some time tonight so I can try and take a look at it. If I don't
figure it out I'll let you know :)

**Comment by Fogest** [comment]
It looks like each comment is now in a div with the class `comment-renderer`. 

The data id for a profile is also on this same div using the `data-author-id`. It looks like the code uses `data-aid` which was likely the old one. 

The text itself is nested a little within the `comment-renderer` div and is in the div with a class of `comment-renderer-text-content`. 

@hadalin You or someone else may need to look at making these changes. I don't know enough about the Javascript and frameworks being used to properly fix this.

**Comment by hadalin** [comment]
Your observations are correct. Will have a look into this.

**Comment by hadalin** [comment]
Ok, managed to show the button and remove the comments. Just have to handle the replies. Will continue tomorrow (hopefully).

**Comment by hadalin** [comment]
Ok, published new version. Can someone test this more rigorously?

**Comment by Fogest** [comment]
Seems to be working for me!
