### ISSUE TITLE
Button disappeared, comments reappeared

### ISSUE THREAD

**Issue by paleguy** [hadalin/chrome-hidefedora#50]
Suddenly i don't see those "meow meow" comments anymore but the reddit comments have returned. i also don't see the button "hide fedora" anymore.. chrome says it's installed and active.. pls help, it's like if my freedom was stolen again.

**Comment by hadalin** [comment]
@paleguy what OS and Chrome version are you using?

**Comment by hadalin** [comment]
This is duplicate of https://github.com/hadalin/chrome-hidefedora/issues/49

**Comment by hadalin** [comment]
@paleguy Log back in to Chrome or install Hide Fedora while logged out.
