### ISSUE TITLE
Not removing fedora comments since the beginning of march.

### ISSUE THREAD

**Issue by BamGfAsRpd** [hadalin/chrome-hidefedora#52]
Since arround march 1st Hide Fedora is not working for me. I've tried removing and adding 2 times now, and it won't even let me add fedora commentors to my local blacklist. It behaves as if it was not installed.

**Comment by Fogest** [comment]
[Try resetting your Google Chrome settings](http://www.howtogeek.com/171924/how-to-reset-your-web-browser-to-its-default-settings/)

**Comment by BamGfAsRpd** [comment]
That fixed it. Thank you so much.
