### ISSUE TITLE
New permissions

### ISSUE THREAD

**Issue by kwillis2291** [hadalin/chrome-hidefedora#53]
Version 1.7.3 can now "read and change your data on jhvisser.com and www.youtube.com".

I've tried searching to understand why the extension now needs this permission. Without any explanation it seems very fishy. Any info/rationale on this change would be appreciated, thanks!

**Comment by Fogest** [comment]
One of them is my site (jhvisser.com) and this is used to get data from my
site regarding the fedoras as well as submit to it. The permissions I
believe were always like that they just may have been altered slightly.
Either way the extension was broken for a little bit and this fixes things.
I can assure you it is still safe. Check out the source code :)

**Comment by Fogest** [comment]
Yeah I just checked what @hadalin did and it actually was the youTube part that changed: 

You can see the changes here: https://github.com/hadalin/chrome-hidefedora/commit/b373120e353b037f8900ff736bdfabf118a21748#diff-5c2c38abbf7eae556fd703040730edd7L13

**Comment by kwillis2291** [comment]
Great, thanks for the clarification, and quick reply!

**Comment by Fogest** [comment]
No problem @kwillis2291 , always good to see people asking these kind of questions!
