### ISSUE TITLE
Maximum number of locally banned profiles?

### ISSUE THREAD

**Issue by danielfox** [hadalin/chrome-hidefedora#54]
I'm having an issue where whenever I try to ban a new profile ALL youtube comments are replaced with "replaced with cat".

I'm guessing this is because there is a maximum number of banned profiles and I've gone over that maximum. I currently have 152 locally banned profiles. Whenever I try to ban another user the above-mentioned bug occurs, and the 153rd profile is listed as "plus.google.com/null" under the banned profiles.

If the maximum size of the local ban list is the problem, could that size be doubled? Or maybe increased by a factor of 10? Thanks!

I'm using chrome 51.0.2704 on OS X, 10.11.6. My other chrome extensions are adblock plus, speed dial 2, session buddy, the great suspender, and WasteNoTime.

edit: I forgot to mention the other extensions I'm using.

**Comment by Fogest** [comment]
The maximum amount of bytes the extension can store is 5 242 880 bytes. If the average profile is about 21 characters in length. Let's assume that 4 bytes are being used for each character. So 21 * 8 = 168. You have 152 profiles. So 152 * 168 = 25536 bytes used. Not even close to the quota. 

I am not sure why it would be breaking. So I don't think storage is the issue, but it does seem like it is a storage problem so it is weird. There is a `unlimitedStorage` permission that can be added to the extension, but I really doubt that it is over the local storage limits imposed by Chrome. Even if I'm way off on my calculation, it still wouldn't be close. 

The extension developer @hadalin may have an idea.

**Comment by hadalin** [comment]
Is this still on issue?

**Comment by danielfox** [comment]
No, it's allowing me to block new profiles now. Thanks!

But now I'm getting a (new?) bug: the comments revealed by "View X replies" do not have a 'HF' option displayed next to them.

**Comment by hadalin** [comment]
🤔

**Comment by hadalin** [comment]
> the comments revealed by "View all X replies" do not have a 'HF' option displayed next to them

Should be fixed now.
