### ISSUE TITLE
No way to add local bans in Chrome????

### ISSUE THREAD

**Issue by HOpefulUser68** [hadalin/chrome-hidefedora#55]
I downloaded Hide Fedora exclusively for the ability to locally hide problem YouTube commenters.

The only thing I see is a little "HF" button by YouTube comments, click on it, it says "Are you sure you want to report Fedora profile?"  No, I don't want to report this person, I just want to hide them locally.  How? 

In options there is a page to see your local bans, but I can't figure out how to add anyone to the list!  THere is no field to enter a term like there is on the adjoining tab for "banned words." 

THanks for your efforts.

**Comment by HOpefulUser68** [comment]
In CHrome, I got bold and decided to click the "HF" button on one of my targets (hoping that would add them to the local list, not merely report them) and initially it turned ALL youtube comments into cats, Meow.   I reloaded the page, all the comments came back (good), even the one I had tried to block (bad), and now the HF button is gone too (worst of all).

**Comment by HOpefulUser68** [comment]
I tried to put their username as a "Banned Words" and that has not worked either.

**Comment by HOpefulUser68** [comment]
In Firefox, I clicked the "HF" button on my target and nothing happened except the HF button went away.  Reloaded the page, HF button has come back but no changes at all in the comments.  I'm feeling so stupid and frustrated!

**Comment by hadalin** [comment]
By reporting a profile you also add them to local ban.
