### ISSUE TITLE
banned profiles isn't working

### ISSUE THREAD

**Issue by msconfig1** [hadalin/chrome-hidefedora#56]
when i click to hf to banned it it isn't work at all. and whan i go to the setting  banned profile  it show   "plus.google.com/null" 

Windows 7 Home Premium K 
chrome 56.0.2924.87 (64-bit)
Hide Fedora 1.8.0

![k-012](https://cloud.githubusercontent.com/assets/25456870/22587460/183cf23c-ea45-11e6-91c9-2744c22416fb.png)
![k-013](https://cloud.githubusercontent.com/assets/25456870/22587459/183a1dc8-ea45-11e6-81dd-5d977485707d.png)

**Comment by birdhall** [comment]
I'm experiencing a different problem - I can ban a profile, but it removes the entire comments section, leaving only the "load more" button: 
![image](https://cloud.githubusercontent.com/assets/1029086/22619735/213b8c66-eab0-11e6-945b-32bd38e632b8.png)


Also this feature in Firefox would be amazing! I tried loading the source code in WebExtensions but it didn't  give any option to configure (no addon icon) nor show any HF button for banning profiles.

**Comment by hadalin** [comment]
@birdhall Have you tried https://addons.mozilla.org/en-US/firefox/addon/hide-fedora/

**Comment by hadalin** [comment]
Yep, YouTube changed HTML again and it seems YouTube comments are not bound to google plus profiles any more.

**Comment by hadalin** [comment]
This is now fixed and is being review by google.

**Comment by hadalin** [comment]
Now version published. You might want to manually [trigger extensions update](http://www.howtogeek.com/64525/how-to-manually-force-google-chrome-to-update-extensions/).

**Comment by birdhall** [comment]
@hadalin I have. Last Updated: March 28, 2016
